### ISSUE TITLE
How can I get the Filter Coefficients？

### ISSUE THREAD

**Issue by sudavida** [KBaur/FiltFilt#1]
The Filter Coefficients used in your test case  are  const values.
How can I get the filter coeffcients  when I use this lib in my program?
Can you give me an adaptive solution？

**Comment by KBaur** [comment]
Hello Sudavida,
the filter coefficients were calculated by Octave (see the main.cpp comment in the example folder)

> Copy paste from the octave filtfilt example:
>     [b, a]=butter(3, 0.1);                  # 5 Hz low-pass filter
>     # b: 2.8982e-03   8.6946e-03   8.6946e-03   2.8982e-03
>     # a: 1.0000  -2.3741   1.9294  -0.5321

With SetCoefficients and GetCoefficients you can alway Set and Get the Filterparameters.
-> See Filt.h
